package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

type structMapping struct {
	sourcePath string
	sourceType string
	targetType string
}

var mappings = []structMapping{
	{sourcePath: "svr_gateway/main.go", sourceType: "GatewayConfig", targetType: "GatewayConfig"},
	{sourcePath: "svr_login/main.go", sourceType: "ServerConfig", targetType: "LoginConfig"},
	{sourcePath: "svr_game/main.go", sourceType: "AppConfig", targetType: "GameConfig"},
}

func main() {
	rootDir, err := resolveRootDir()
	if err != nil {
		exitWithError(err)
	}

	fset := token.NewFileSet()
	var generated bytes.Buffer
	generated.WriteString("// Code generated by tools/generate_supervisor_configs.go; DO NOT EDIT.\n\n")
	generated.WriteString("package main\n\n")

	for _, mapping := range mappings {
		sourceFile := filepath.Join(rootDir, filepath.FromSlash(mapping.sourcePath))
		structType, err := loadStructType(fset, sourceFile, mapping.sourceType)
		if err != nil {
			exitWithError(err)
		}
		renderStruct(&generated, fset, mapping.targetType, structType)
		generated.WriteByte('\n')
	}

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		exitWithError(fmt.Errorf("format generated file failed: %w", err))
	}

	outputPath := filepath.Join(rootDir, "svr_supervisor", "config_types_generated.go")
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		exitWithError(fmt.Errorf("write generated file failed: %w", err))
	}
}

func resolveRootDir() (string, error) {
	if len(os.Args) > 1 {
		return filepath.Abs(os.Args[1])
	}
	return os.Getwd()
}

func loadStructType(fset *token.FileSet, path string, typeName string) (*ast.StructType, error) {
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s failed: %w", path, err)
	}

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != typeName {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				return nil, fmt.Errorf("%s in %s is not a struct", typeName, path)
			}
			return structType, nil
		}
	}

	return nil, fmt.Errorf("type %s not found in %s", typeName, path)
}

func renderStruct(dst *bytes.Buffer, fset *token.FileSet, typeName string, structType *ast.StructType) {
	dst.WriteString("type ")
	dst.WriteString(typeName)
	dst.WriteString(" struct {\n")

	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			exitWithError(fmt.Errorf("embedded field is not supported in %s", typeName))
		}

		var fieldNames []string
		for _, name := range field.Names {
			fieldNames = append(fieldNames, name.Name)
		}

		dst.WriteByte('\t')
		dst.WriteString(strings.Join(fieldNames, ", "))
		dst.WriteByte(' ')
		dst.WriteString(renderNode(fset, field.Type))
		if field.Tag != nil {
			dst.WriteByte(' ')
			dst.WriteString(field.Tag.Value)
		}
		dst.WriteByte('\n')
	}

	dst.WriteString("}\n")
}

func renderNode(fset *token.FileSet, node ast.Node) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, node); err != nil {
		exitWithError(fmt.Errorf("render AST node failed: %w", err))
	}
	return buf.String()
}

func exitWithError(err error) {
	fmt.Fprintln(os.Stderr, "[ERROR]", err.Error())
	os.Exit(1)
}
