// Code generated by tools/generate_supervisor_configs.go; DO NOT EDIT.

package main

type GatewayConfig struct {
	GatewayPort       int    `json:"gateway_port"`
	JWTSecret         string `json:"jwt_secret"`
	ProxyTimeoutMS    int64  `json:"proxy_timeout_ms"`
	LoginRoutePath    string `json:"login_route_path"`
	LoginTargetPath   string `json:"login_target_path"`
	RegisterPath      string `json:"register_path"`
	HeartbeatPath     string `json:"heartbeat_path"`
	LeaseTimeoutSec   int64  `json:"lease_timeout_sec"`
	SupersedeDelaySec int64  `json:"supersede_delay_sec"`
	GameStickyTTLSec  int64  `json:"game_sticky_ttl_sec"`
}

type LoginConfig struct {
	WXAppID              string `json:"wx_app_id"`
	WXAppSecret          string `json:"wx_app_secret"`
	LoginPort            int    `json:"login_port"`
	JWTSecret            string `json:"jwt_secret"`
	GatewayHost          string `json:"gateway_host"`
	GatewayPort          int    `json:"gateway_port"`
	GatewayRegisterPath  string `json:"gateway_register_path"`
	GatewayHeartbeatPath string `json:"gateway_heartbeat_path"`
	ReportIP             string `json:"report_ip"`
	ServerID             string `json:"server_id"`
}

type GameConfig struct {
	GamePort             int    `json:"game_port"`
	MainCollection       string `json:"main_collection"`
	GatewayHost          string `json:"gateway_host"`
	GatewayPort          int    `json:"gateway_port"`
	GatewayRegisterPath  string `json:"gateway_register_path"`
	GatewayHeartbeatPath string `json:"gateway_heartbeat_path"`
	ReportIP             string `json:"report_ip"`
	ServerID             string `json:"server_id"`
	GeneratorID          uint16 `json:"generator_id"`
	PlayerCacheTTLSec    int64  `json:"player_cache_ttl_sec"`
	PlayerFlushSec       int64  `json:"player_flush_interval_sec"`
	DataDir              string `json:"data_dir"`
	CheatModeOn          int    `json:"cheat_mode_on"`
}
